const $=s=>document.querySelector(s);const screens={char:$('#screen-character'),game:$('#screen-game'),upgrade:$('#screen-upgrade'),win:$('#screen-win'),lose:$('#screen-lose')};
const STAT_ICONS={pv:'sprites/hud/stats/PV.png',damage:'sprites/hud/stats/damage.png',as:'sprites/hud/stats/as.png',crit:'sprites/hud/stats/crit.png',resistance:'sprites/hud/stats/resistance.png',magic:'sprites/hud/stats/Magiquedamage.png'};const stats=['pv','damage','as','crit','resistance','magic'];
const state={players:[],wave:1,time:60,playing:false,last:0,spawn:0,enemies:[],projectiles:[],kills:0,tab:'wave'};const canvas=$('#game'),ctx=canvas.getContext('2d');let W=0,H=0;const keys={};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(e.key.toLowerCase()))e.preventDefault()});addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
const controls=[{u:'w',d:'s',l:'a',r:'d',name:'WASD'},{u:'arrowup',d:'arrowdown',l:'arrowleft',r:'arrowright',name:'ARROWS'},{u:'i',d:'k',l:'j',r:'l',name:'IJKL'},{u:'8',d:'5',l:'4',r:'6',name:'NUMPAD'}];
function spriteForPlayer(p){return p.frame==='idle'?'sprites/The mad/themad.png':p.frame==='1'?'sprites/The mad/themad1.png':'sprites/The mad/themad2.png'}
function makePlayer(i){return {id:i,x:W*(.35+i*.1),y:H*.55,hp:10,maxHp:10,damage:5,as:1.5,crit:0,resistance:0,magic:0,speed:170,frame:'idle',cool:0,alive:true}}
function setupSlots(){const root=$('#player-slots');root.innerHTML='';for(let i=0;i<4;i++){const b=document.createElement('button');b.className='player-slot joined';b.innerHTML=`<div class="label">PLAYER ${i+1}</div><div class="status">READY · ${controls[i].name}</div>`;b.onclick=()=>b.classList.toggle('joined');root.appendChild(b)}}setupSlots();$('#champion-preview').src='sprites/The mad/themad.png';
$('#start-btn').onclick=()=>{const slots=[...document.querySelectorAll('.player-slot')];state.players=slots.filter(s=>s.classList.contains('joined')).map((_,i)=>makePlayer(i));if(!state.players.length)state.players=[makePlayer(0)];applyPassive();resize();state.wave=1;state.time=60;state.enemies=[];state.projectiles=[];state.kills=0;state.playing=true;state.spawn=0;show('game');state.last=performance.now();requestAnimationFrame(loop)};
$('#again-win').onclick=$('#again-lose').onclick=()=>{show('char');setupSlots()};function show(n){Object.values(screens).forEach(x=>x.classList.remove('active'));screens[n].classList.add('active')}
function applyPassive(){for(const p of state.players){p.maxHp*=1.1;p.hp=p.maxHp;p.damage*=1.1;p.as*=1.65;p.crit*=1.1;p.resistance*=1.1;p.magic*=1.1;p.speed*=1.1}} // ALL STATS +10%, ATTACK SPEED +50%
function resize(){W=canvas.width=innerWidth;H=canvas.height=innerHeight;state.players.forEach((p,i)=>{if(p.x>W||p.y>H){p.x=W*(.35+i*.1);p.y=H*.55}})}addEventListener('resize',resize);resize();
function spawnEnemy(){const side=Math.floor(Math.random()*4),pad=40;let x=0,y=0;if(side===0){x=-pad;y=Math.random()*H}else if(side===1){x=W+pad;y=Math.random()*H}else if(side===2){x=Math.random()*W;y=-pad}else{x=Math.random()*W;y=H+pad}state.enemies.push({x,y,hp:2+Math.floor(state.wave*.45),maxHp:2+Math.floor(state.wave*.45),speed:45+state.wave*2,r:15})}
function nearest(p){let best=null,d=Infinity;for(const e of state.enemies){const q=(e.x-p.x)**2+(e.y-p.y)**2;if(q<d){d=q;best=e}}return best}
function shoot(p,target){const dx=target.x-p.x,dy=target.y-p.y,len=Math.hypot(dx,dy)||1;const dmg=p.damage*(Math.random()*100<p.crit?2:1);state.projectiles.push({x:p.x,y:p.y,vx:dx/len*520,vy:dy/len*520,dmg,life:1});p.frame=dx>=0?'1':'2'}
function movePlayer(p,c,dt){let dx=(keys[c.r]?1:0)-(keys[c.l]?1:0),dy=(keys[c.d]?1:0)-(keys[c.u]?1:0);if(dx||dy){const l=Math.hypot(dx,dy);p.x+=dx/l*p.speed*dt;p.y+=dy/l*p.speed*dt}p.x=Math.max(18,Math.min(W-18,p.x));p.y=Math.max(70,Math.min(H-18,p.y))}
function update(dt){state.time-=dt;if(state.time<=0){state.time=0;state.playing=false;state.enemies=[];if(state.wave>=10){show('win');return}openUpgrade();return}state.spawn-=dt;const interval=Math.max(.08,.42-state.wave*.025);if(state.spawn<=0){state.spawn=interval;for(let i=0;i<(state.wave>=5?2:1);i++)spawnEnemy()}
for(let i=0;i<state.players.length;i++){const p=state.players[i];if(!p.alive)continue;movePlayer(p,controls[i],dt);p.cool-=dt;const t=nearest(p);if(t&&p.cool<=0){shoot(p,t);p.cool=1/p.as}else if(!t)p.frame='idle'}
for(const e of state.enemies){let target=null,dd=Infinity;for(const p of state.players)if(p.alive){const d=(p.x-e.x)**2+(p.y-e.y)**2;if(d<dd){dd=d;target=p}}if(target){const dx=target.x-e.x,dy=target.y-e.y,l=Math.hypot(dx,dy)||1;e.x+=dx/l*e.speed*dt;e.y+=dy/l*e.speed*dt;if(Math.hypot(dx,dy)<e.r+14){target.hp-=Math.max(0,1-target.resistance/100);e.x-=dx/l*8;e.y-=dy/l*8;if(target.hp<=0){target.hp=0;target.alive=false}}}}
for(const b of state.projectiles){b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of state.enemies)if((e.x-b.x)**2+(e.y-b.y)**2<(e.r+5)**2){e.hp-=b.dmg;b.life=0;if(e.hp<=0){state.kills++;e.dead=true}break}}state.projectiles=state.projectiles.filter(b=>b.life>0);state.enemies=state.enemies.filter(e=>!e.dead);if(state.players.every(p=>!p.alive)){state.playing=false;$('#lose-text').textContent=`WAVE ${state.wave} · ${state.kills} KILLS`;show('lose')}}
function draw(){ctx.fillStyle='#70757b';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#666b70';for(let x=0;x<W;x+=48){ctx.beginPath();ctx.moveTo(x,60);ctx.lineTo(x,H);ctx.stroke()}for(let y=60;y<H;y+=48){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}for(const b of state.projectiles){ctx.fillStyle='#eee';ctx.fillRect(b.x-3,b.y-3,6,6)}for(const e of state.enemies){ctx.fillStyle='#25282b';ctx.beginPath();ctx.arc(e.x,e.y,e.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#aaa';ctx.fillRect(e.x-15,e.y-e.r-7,30,3);ctx.fillStyle='#eee';ctx.fillRect(e.x-15,e.y-e.r-7,30*Math.max(0,e.hp/e.maxHp),3)}for(const p of state.players){if(!p.alive)continue;const img=new Image();img.src=spriteForPlayer(p);ctx.imageSmoothingEnabled=false;ctx.drawImage(img,p.x-28,p.y-28,56,56);ctx.fillStyle='#151719';ctx.fillRect(p.x-22,p.y+30,44,5);ctx.fillStyle='#ddd';ctx.fillRect(p.x-22,p.y+30,44*(p.hp/p.maxHp),5)}}
function updateHud(){const m=Math.max(0,Math.ceil(state.time));$('#wave').textContent=`WAVE ${state.wave}/10`;$('#timer').textContent=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;$('#alive').textContent=`ENEMIES ${state.enemies.length}`;$('#player-hud').innerHTML=state.players.map((p,i)=>`<div class="p-hud ${p.alive?'':'dead'}"><b>P${i+1}</b> · THE MAD<div class="bar"><div class="fill" style="width:${p.hp/p.maxHp*100}%"></div></div><small>${Math.ceil(p.hp)}/${Math.ceil(p.maxHp)} PV · ${Math.ceil(p.damage)} DMG · ${p.as.toFixed(2)} AS</small></div>`).join('')}
function loop(t){if(!state.playing)return;const dt=Math.min(.033,(t-state.last)/1000||0);state.last=t;update(dt);draw();updateHud();if(state.playing)requestAnimationFrame(loop)}function openUpgrade(){show('upgrade');state.tab='wave';renderUpgrades()}
function renderUpgrades(){const grid=$('#upgrade-grid');grid.innerHTML='';for(const s of stats){const v=s==='damage'?1:s==='as'?.15:s==='pv'?2:s==='crit'||s==='resistance'?5:1;const b=document.createElement('button');b.className='upgrade';b.innerHTML=`<img src="${STAT_ICONS[s]}"><h3>${s.toUpperCase()}</h3><p>+${v}${s==='crit'||s==='resistance'?'%':''}</p>`;b.onclick=()=>pickUpgrade(s,v);grid.appendChild(b)}}
function pickUpgrade(s,v){const p=state.players.find(x=>x.alive)||state.players[0];if(s==='pv'){p.maxHp+=v;p.hp=Math.min(p.maxHp,p.hp+v)}else p[s]+=v;state.wave++;state.time=60;state.enemies=[];state.projectiles=[];state.playing=true;state.spawn=0;show('game');state.last=performance.now();requestAnimationFrame(loop)}
$('#tab-wave').onclick=()=>{state.tab='wave';renderUpgrades()};$('#tab-character').onclick=()=>{state.tab='character';renderCharacterTab()};function renderCharacterTab(){$('#upgrade-grid').innerHTML=`<button class="upgrade"><img src="sprites/The mad/themad.png"><h3>THE MAD</h3><p>PASSIVE · ALL STATS +10%<br>ATTACK SPEED +50%</p></button>`}
addEventListener('gamepadconnected',()=>requestAnimationFrame(gamepadLoop));function gamepadLoop(){for(const g of navigator.getGamepads()){if(!g)continue;if(g.buttons[5]?.pressed&&screens.upgrade.classList.contains('active')){state.tab='character';renderCharacterTab()}if(g.buttons[4]?.pressed&&screens.upgrade.classList.contains('active')){state.tab='wave';renderUpgrades()}}requestAnimationFrame(gamepadLoop)}
